# Generated by Django 5.0.7 on 2026-09-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('unit', models.CharField(choices=[('250 g', '250 g'), ('500 g', '500 g'), ('kg', 'kg'), ('2 kg', '2 kg'), ('5 kg', '5 kg'), ('piece', 'piece'), ('dozen', 'dozen'), ('bunch', 'bunch')], default='kg', max_length=10)),
                ('price', models.PositiveIntegerField(help_text='MRP in ₹')),
                ('sale_price', models.PositiveIntegerField(help_text='Selling price in ₹')),
                ('stock', models.FloatField(default=0)),
                ('low_stock_at', models.FloatField(default=10)),
                ('min_qty', models.FloatField(default=1)),
                ('max_qty', models.FloatField(default=5)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('tag', models.CharField(blank=True, max_length=40)),
                ('gst_percent', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-featured', 'name'],
            },
        ),
    ]
