# Generated by Django 5.0.7 on 2026-09-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('delivery_charge', models.PositiveIntegerField(default=0)),
                ('min_order_value', models.PositiveIntegerField(default=0)),
                ('free_above_value', models.PositiveIntegerField(default=0, help_text='0 disables free-delivery threshold')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('max_orders', models.PositiveIntegerField(default=30)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
