# Generated by Django 5.0.7 on 2026-09-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(blank=True, default='🧺', max_length=10)),
                ('normal_price', models.PositiveIntegerField()),
                ('combo_price', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_stack_with_coupon', models.BooleanField(default=True)),
                ('combo_stack_with_coupon', models.BooleanField(default=False)),
                ('multiple_coupons', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=1)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='discounts.combo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('type', models.CharField(choices=[('FLAT', 'Flat ₹'), ('PERCENT', 'Percentage %')], max_length=10)),
                ('amount', models.FloatField(help_text='Flat rupees or percent, depending on type')),
                ('min_order_value', models.PositiveIntegerField(default=0)),
                ('max_discount', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(default=1000)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('apartment_only', models.ForeignKey(blank=True, help_text='Leave blank to make this coupon valid for all apartments', null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.coupon')),
            ],
        ),
    ]
